= SOAP to REST

Contract-first API development wrapping an existing SOAP service, implemented using Eclipse Che

* Audience: Developers and Architects

Another important use case in developing API's is to take an existing
legacy SOAP service and wrap it with a new RESTful endpoint. This SOAP
to REST transformation is implemented in the API service layer (Fuse).
This lab will walk you through taking an existing SOAP contract (WSDL),
converting it to Java POJO's and exposing it using Camel RESTdsl.

Eclipse Che, our online IDE, provides important functionality for
implementing API services. In this lab you can see how our Eclipse Che
and Fuse can help with SOAP to REST transformation on OpenShift.


== Generating REST resources for the soap2rest App

=== Enabling the Codegen plugin in the soap2rest App


TODO: info about the SOAP & soap2rest templates & repos that were created

. Log in to the link:{che-url}[Che, window="_blank"] Dashboard.

. TODO steps to setup a workspace and import the soap2rest project from gitea

. Open the `dayinthelife-import/location-soap2rest` project. Open the `pom.xml` file and scroll to the bottom. Uncomment out the `cxf-codegen-plugin` entry at the bottom. Update the `<wsdl>` entry with your fully qualified WSDL 
URL e.g.
`http://location-soap-{user}-walkthrough-three.{openshift-router-suffix}/ws/location?wsdl`.

. TODO link for actual wsdl
. TODO be careful of 63 char limit with the Route name.

[type=verification]
The wsdl file is served successfully.

=== Generating POJOs from the WSDL contract

. We now need to generate the POJO objects from the WSDL contract. To
do this, open the Terminal tab and run the below commands:
TODO: verify below folder is correct for the repo we end up using
[source,java]
----
cd /projects/dayinthelife-integration/projects/location-soap2rest/
mvn generate-sources
----

[type=verification]
Once the script has completed, navigate back to the `src/main/java/com/redhat` folder. Notice that there are a bunch of new POJO classes that were created by the Maven script.


== Adding a REST route to the soap2rest App

=== Adding the REST route

. We need to create our Camel route implementation and create the RESTful
endpoint. To do this, add the following block below the `// ADD LOCATION ROUTE HERE` comment
+
[source,java]
----
    rest("/location").description("Location information")
        .produces("application/json")
        .get("/contact/{id}").description("Location Contact Info")
            .responseMessage().code(200).message("Data successfully returned").endResponseMessage()
            .to("direct:getalllocationphone");
----
+
. We also need to update the cxf value below the `// UPDATE CXF VALUE HERE` comment to `""cxf://http://location-soap-userX.apps.GUID.openshiftworkshop.com/ws/location?serviceClass=com.redhat.LocationDetailServicePortType&defaultOperationName=contact"`
. TODO: ^^ should be dynamically set by webapp

=== Testing the REST route

. Now that we have our API service implementation, we can try to test
this 'locally' in Che. Navigate back to the *Terminal* tab and run
`MAVEN_OPTS="-Xmx1000m" mvn spring-boot:run -f /projects/dayinthelife-integration/projects/location-soap2rest`. 
. Once the application starts, navigate to the Servers window and
click on the URL corresponding to port 8080. A new tab should appear.
. In the new tab, append the URL with the following URI: `/location/contact/2`.

[type=verification]
A contact should be returned from the endpoint.

== Deploying the soap2rest App to OpenShift

=== Commit & push repository changes

Now that we've successfully tested our new SOAP to REST service
locally, we can deploy it to OpenShift. First we need push our file changes back to the git repository.

. TODO git steps in Che

. TODO kick off a build (if webhook isn't possible)

[type=verification]
TODO navigate to the route of the deployed soap2rest app and verify the /location/contact/2 endpoint

== Managing the REST route

=== TODO

TODO: 3scale

[type=verification]
TODO call the 3Scale apicast staging route with the user_key param.